project_name: gordon
release:
  github:
    owner: kyoh86
    name: gordon
brews:
- install: |
    bin.install "gordon"
    man1.install "gordon.1"
  github:
    owner: kyoh86
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/kyoh86/gordon
  description: GO Released binaries DOwNloader
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: gordon
  hooks:
    pre: make man
archives:
- id: gzip
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  - gordon.1
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
