.PHONY: gen lint test install man FORCE
FORCE:

VERSION := `git vertag get`
COMMIT  := `git rev-parse HEAD`

gen-clear:
	rm internal/**/*_gen.go

gen: gen-clear internal/env/go_dist_gen.go
	go generate -x ./...
	interfacer -for github.com/kyoh86/gordon/internal/env.Access -as command.Env -o internal/command/env_gen.go
	mockgen -source internal/command/env_gen.go -destination internal/command/env_mock_test.go -package command_test
	
	interfacer -for github.com/kyoh86/gordon/internal/env.Access -as gordon.Env -o internal/gordon/env_gen.go
	mockgen -source internal/gordon/env_gen.go -destination internal/gordon/env_mock_test.go -package gordon_test
	
	interfacer -for github.com/kyoh86/gordon/internal/hub.Client -as command.HubClient -o internal/command/hub_gen.go
	mockgen -source internal/command/hub_gen.go -destination internal/command/hub_mock_test.go -package command_test

internal/env/go_dist_gen.go: FORCE
	@echo "// Code generated by 'make gen'; DO NOT EDIT." > $@
	@echo "" >> $@
	@echo "package env" >> $@
	@echo "" >> $@
	@echo -n "var goDists = map[string]map[string]byte" >> $@
	@go tool dist list -json | jq -rcM 'reduce .[]as$$o({};.*{($$o.GOOS):{($$o.GOARCH):1}})' >> $@
	@echo -n "var goArchs = map[string]byte" >> $@
	@go tool dist list -json | jq -rcM 'reduce .[]as$$o({};.*{($$o.GOARCH):1})' >> $@
	@gofmt -s -w $@

lint: gen
	golangci-lint run

test: lint
	go test -v --race ./...

install: test
	go install -a -ldflags "-X=main.version=$(VERSION) -X=main.commit=$(COMMIT)" ./...

man:
	go run . --help-man > gordon.1
