.PHONY: gen lint test install man FORCE
FORCE:

VERSION := `git vertag get`
COMMIT  := `git rev-parse HEAD`

gen: internal/context/go_dist_gen.go
	go generate ./...

internal/context/go_dist_gen.go: FORCE
	@echo "// Code generated by 'make gen'; DO NOT EDIT." > $@
	@echo "" >> $@
	@echo "package context" >> $@
	@echo "" >> $@
	@echo -n "var goDists = map[string]map[string]byte" >> $@
	@go tool dist list -json | jq -rcM 'reduce .[]as$$o({};.*{($$o.GOOS):{($$o.GOARCH):1}})' >> $@
	@echo -n "var goArchs = map[string]byte" >> $@
	@go tool dist list -json | jq -rcM 'reduce .[]as$$o({};.*{($$o.GOARCH):1})' >> $@
	@gofmt -s -w $@

lint: gen
	golangci-lint run

test: lint
	go test -v --race ./...

install: test
	go install -a -ldflags "-X=main.version=$(VERSION) -X=main.commit=$(COMMIT)" ./...

man:
	go run main.go --help-man > gordon.1
