// Code generated by main.go DO NOT EDIT.

package env

import (
	"fmt"
	types "github.com/kyoh86/appenv/types"
	"io"
)

type Config struct {
	yml YAML
}

func GetConfig(yamlReader io.Reader) (config Config, err error) {
	yml, err := loadYAML(yamlReader)
	if err != nil {
		return config, err
	}
	return buildConfig(yml)
}

func buildConfig(yml YAML) (config Config, err error) {
	config.yml = yml
	return
}

func (c *Config) Save(yamlWriter io.Writer) error {
	if err := saveYAML(yamlWriter, &c.yml); err != nil {
		return err
	}
	return nil
}

func PropertyNames() []string {
	return []string{"github.host", "github.user", "history.file", "history.save", "extract.modes", "extract.exclude", "extract.include", "architecture", "os", "root", "hooks"}
}

func (a *Config) Property(name string) (types.Config, error) {
	switch name {
	case "github.host":
		return &githubHostConfig{parent: a}, nil
	case "github.user":
		return &githubUserConfig{parent: a}, nil
	case "history.file":
		return &historyFileConfig{parent: a}, nil
	case "history.save":
		return &historySaveConfig{parent: a}, nil
	case "extract.modes":
		return &extractModesConfig{parent: a}, nil
	case "extract.exclude":
		return &extractExcludeConfig{parent: a}, nil
	case "extract.include":
		return &extractIncludeConfig{parent: a}, nil
	case "architecture":
		return &architectureConfig{parent: a}, nil
	case "os":
		return &osConfig{parent: a}, nil
	case "root":
		return &rootConfig{parent: a}, nil
	case "hooks":
		return &hooksConfig{parent: a}, nil
	}
	return nil, fmt.Errorf("invalid property name %q", name)
}

type githubHostConfig struct {
	parent *Config
}

func (a *githubHostConfig) Get() (string, error) {
	{
		p := a.parent.yml.GithubHost
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *githubHostConfig) Set(value string) error {
	{
		p := a.parent.yml.GithubHost
		if p == nil {
			p = new(GithubHost)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.GithubHost = p
	}
	return nil
}

func (a *githubHostConfig) Unset() {
	a.parent.yml.GithubHost = nil
}

type githubUserConfig struct {
	parent *Config
}

func (a *githubUserConfig) Get() (string, error) {
	{
		p := a.parent.yml.GithubUser
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *githubUserConfig) Set(value string) error {
	{
		p := a.parent.yml.GithubUser
		if p == nil {
			p = new(GithubUser)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.GithubUser = p
	}
	return nil
}

func (a *githubUserConfig) Unset() {
	a.parent.yml.GithubUser = nil
}

type historyFileConfig struct {
	parent *Config
}

func (a *historyFileConfig) Get() (string, error) {
	{
		p := a.parent.yml.HistoryFile
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *historyFileConfig) Set(value string) error {
	{
		p := a.parent.yml.HistoryFile
		if p == nil {
			p = new(HistoryFile)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.HistoryFile = p
	}
	return nil
}

func (a *historyFileConfig) Unset() {
	a.parent.yml.HistoryFile = nil
}

type historySaveConfig struct {
	parent *Config
}

func (a *historySaveConfig) Get() (string, error) {
	{
		p := a.parent.yml.HistorySave
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *historySaveConfig) Set(value string) error {
	{
		p := a.parent.yml.HistorySave
		if p == nil {
			p = new(HistorySave)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.HistorySave = p
	}
	return nil
}

func (a *historySaveConfig) Unset() {
	a.parent.yml.HistorySave = nil
}

type extractModesConfig struct {
	parent *Config
}

func (a *extractModesConfig) Get() (string, error) {
	{
		p := a.parent.yml.ExtractModes
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *extractModesConfig) Set(value string) error {
	{
		p := a.parent.yml.ExtractModes
		if p == nil {
			p = new(ExtractModes)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.ExtractModes = p
	}
	return nil
}

func (a *extractModesConfig) Unset() {
	a.parent.yml.ExtractModes = nil
}

type extractExcludeConfig struct {
	parent *Config
}

func (a *extractExcludeConfig) Get() (string, error) {
	{
		p := a.parent.yml.ExtractExclude
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *extractExcludeConfig) Set(value string) error {
	{
		p := a.parent.yml.ExtractExclude
		if p == nil {
			p = new(ExtractExclude)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.ExtractExclude = p
	}
	return nil
}

func (a *extractExcludeConfig) Unset() {
	a.parent.yml.ExtractExclude = nil
}

type extractIncludeConfig struct {
	parent *Config
}

func (a *extractIncludeConfig) Get() (string, error) {
	{
		p := a.parent.yml.ExtractInclude
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *extractIncludeConfig) Set(value string) error {
	{
		p := a.parent.yml.ExtractInclude
		if p == nil {
			p = new(ExtractInclude)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.ExtractInclude = p
	}
	return nil
}

func (a *extractIncludeConfig) Unset() {
	a.parent.yml.ExtractInclude = nil
}

type architectureConfig struct {
	parent *Config
}

func (a *architectureConfig) Get() (string, error) {
	{
		p := a.parent.yml.Architecture
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *architectureConfig) Set(value string) error {
	{
		p := a.parent.yml.Architecture
		if p == nil {
			p = new(Architecture)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.Architecture = p
	}
	return nil
}

func (a *architectureConfig) Unset() {
	a.parent.yml.Architecture = nil
}

type osConfig struct {
	parent *Config
}

func (a *osConfig) Get() (string, error) {
	{
		p := a.parent.yml.OS
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *osConfig) Set(value string) error {
	{
		p := a.parent.yml.OS
		if p == nil {
			p = new(OS)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.OS = p
	}
	return nil
}

func (a *osConfig) Unset() {
	a.parent.yml.OS = nil
}

type rootConfig struct {
	parent *Config
}

func (a *rootConfig) Get() (string, error) {
	{
		p := a.parent.yml.Root
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *rootConfig) Set(value string) error {
	{
		p := a.parent.yml.Root
		if p == nil {
			p = new(Root)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.Root = p
	}
	return nil
}

func (a *rootConfig) Unset() {
	a.parent.yml.Root = nil
}

type hooksConfig struct {
	parent *Config
}

func (a *hooksConfig) Get() (string, error) {
	{
		p := a.parent.yml.Hooks
		if p != nil {
			text, err := p.MarshalText()
			return string(text), err
		}
	}
	return "", nil
}

func (a *hooksConfig) Set(value string) error {
	{
		p := a.parent.yml.Hooks
		if p == nil {
			p = new(Hooks)
		}
		if err := p.UnmarshalText([]byte(value)); err != nil {
			return err
		}
		a.parent.yml.Hooks = p
	}
	return nil
}

func (a *hooksConfig) Unset() {
	a.parent.yml.Hooks = nil
}
