// Code generated by interfacer; DO NOT EDIT

package env

import (
)

// Env is an interface generated for "github.com/kyoh86/gordon/internal/env.Access".
type Env interface {
	Architecture() string
	GithubHost() string
	GithubUser() string
	Hooks() []string
	OS() string
	Root() string
}
