// Code generated by 'make gen'; DO NOT EDIT.

package env

var goDists = map[string]map[string]byte{"aix": {"ppc64": 1}, "android": {"386": 1, "amd64": 1, "arm": 1, "arm64": 1}, "darwin": {"amd64": 1, "arm64": 1}, "dragonfly": {"amd64": 1}, "freebsd": {"386": 1, "amd64": 1, "arm": 1, "arm64": 1}, "illumos": {"amd64": 1}, "js": {"wasm": 1}, "linux": {"386": 1, "amd64": 1, "arm": 1, "arm64": 1, "mips": 1, "mips64": 1, "mips64le": 1, "mipsle": 1, "ppc64": 1, "ppc64le": 1, "riscv64": 1, "s390x": 1}, "netbsd": {"386": 1, "amd64": 1, "arm": 1, "arm64": 1}, "openbsd": {"386": 1, "amd64": 1, "arm": 1, "arm64": 1}, "plan9": {"386": 1, "amd64": 1, "arm": 1}, "solaris": {"amd64": 1}, "windows": {"386": 1, "amd64": 1, "arm": 1}}
var goArchs = map[string]byte{"ppc64": 1, "386": 1, "amd64": 1, "arm": 1, "arm64": 1, "wasm": 1, "mips": 1, "mips64": 1, "mips64le": 1, "mipsle": 1, "ppc64le": 1, "riscv64": 1, "s390x": 1}
