// Code generated by interfacer; DO NOT EDIT

package command

import (
)

// Env is an interface generated for "github.com/kyoh86/gordon/internal/env.Access".
type Env interface {
	Architecture() string
	Bin() string
	Cache() string
	GithubHost() string
	GithubUser() string
	Hooks() []string
	Man() string
	OS() string
}
