// Code generated by MockGen. DO NOT EDIT.
// Source: internal/env/env_gen.go

// Package command_test is a generated GoMock package.
package command_test

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEnv is a mock of Env interface
type MockEnv struct {
	ctrl     *gomock.Controller
	recorder *MockEnvMockRecorder
}

// MockEnvMockRecorder is the mock recorder for MockEnv
type MockEnvMockRecorder struct {
	mock *MockEnv
}

// NewMockEnv creates a new mock instance
func NewMockEnv(ctrl *gomock.Controller) *MockEnv {
	mock := &MockEnv{ctrl: ctrl}
	mock.recorder = &MockEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnv) EXPECT() *MockEnvMockRecorder {
	return m.recorder
}

// GithubHost mocks base method
func (m *MockEnv) GithubHost() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GithubHost")
	ret0, _ := ret[0].(string)
	return ret0
}

// GithubHost indicates an expected call of GithubHost
func (mr *MockEnvMockRecorder) GithubHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GithubHost", reflect.TypeOf((*MockEnv)(nil).GithubHost))
}

// GithubUser mocks base method
func (m *MockEnv) GithubUser() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GithubUser")
	ret0, _ := ret[0].(string)
	return ret0
}

// GithubUser indicates an expected call of GithubUser
func (mr *MockEnvMockRecorder) GithubUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GithubUser", reflect.TypeOf((*MockEnv)(nil).GithubUser))
}

// Hooks mocks base method
func (m *MockEnv) Hooks() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Hooks indicates an expected call of Hooks
func (mr *MockEnvMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockEnv)(nil).Hooks))
}

// Root mocks base method
func (m *MockEnv) Root() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(string)
	return ret0
}

// Root indicates an expected call of Root
func (mr *MockEnvMockRecorder) Root() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockEnv)(nil).Root))
}
