// Code generated by interfacer; DO NOT EDIT

package command

import (
	"context"
	"github.com/google/go-github/v29/github"
	"github.com/kyoh86/gogh/gogh"
	"io"
)

// HubClient is an interface generated for "github.com/kyoh86/gordon/internal/hub.Client".
type HubClient interface {
	Asset(context.Context, *gogh.Repo, int64) (io.ReadCloser, error)
	LatestRelease(context.Context, *gogh.Repo) (*github.RepositoryRelease, error)
	Release(context.Context, *gogh.Repo, string) (*github.RepositoryRelease, error)
}
